### ISSUE TITLE
Not working in Sketch 3.4.3 and 3.4.2

### ISSUE THREAD

**Issue by asyla** [t32k/material-design-color-palette#5]
Hi! 
I'm using Sketch 3.4.3 and OS X 10.10.5. Unfortunately, the plugin didn't even install (from Toolbox):

![image](https://cloud.githubusercontent.com/assets/14801014/11682170/e261e8a0-9e6b-11e5-847d-755c1337d508.png)

And it never appears in the plugin folder:
![image](https://cloud.githubusercontent.com/assets/14801014/11682199/01d10a90-9e6c-11e5-96b2-c83a64367e8f.png)

Could you please help me?
Thanks!)

**Comment by t32k** [comment]
![screen shot 0027-12-14 at 17 56 03](https://cloud.githubusercontent.com/assets/86519/11776632/fe5c2a38-a28b-11e5-9cb2-391a8954d395.png)

@asyla 

Sorry, I changed my plugin name. That's why you cannot install the plugin from Sketch Toolbox.
Fortunately, Sketch Toolbox owner accepted PR to change my plugin name, so you can do that now!
Please install `Material Design Color Palette`, it's new,  not `Material Design Color Palette Sketch Plugin`.

**Comment by asyla** [comment]
Great, thank you so much! It really works now)
